### ISSUE TITLE
Use unjs/unstorage ? 

### ISSUE THREAD

**Issue by Celibioux** [dvanmali/surrealdb-nuxt-starter#2]
Nice work bro ! I have just one question if you have time ! Woudn't be nice to use unjs/unstorage method as the maker of unjs/Nitro & unjs/Unstorage seeks to make a connector for Surrealdb

**Comment by dvanmali** [comment]
Hi @Celibioux. Apologies for the delay with the response. Cool package, I never knew it existed. After looking through the docs, I did notice a few limitations with using their built-in storage.

- With surrealdb, you can query relationships and nested data structures. The package limits a user in only performing CRUD operations on a Table and Items. This can result in what could have been one query call, with multiple CRUD calls.
- With unstorage, you can only select entire tables and items. We can't specify specific fields. An "all or nothing" may be good in certain implementations but not in all use cases.

Using the native surrealdb driver provides greater support for SurrealDb specific features.

**Comment by Celibioux** [comment]
Thank you so much for talking the time for this great explaination :)
